name: Build Vprofile

on:
  push:
    branches: [main, develop, docker]
  pull_request:
    branches: [main, develop, docker]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven if branch = copy-docker
        if: github.ref == 'refs/heads/docker'
        run: mvn clean package -DskipTests        

  testing:
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Tests
        run: mvn test

      - name: Use Var
        run: echo $SUPER_VARIABLE
        env:
          SUPER_VARIABLE: ${{ vars.SUPER_VARIABLE }}

      - name: Maven Checkstyle
        run: mvn checkstyle:checkstyle

  Security-Scanner:
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-results.json

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json
