name: Build Vprofile

on:
  push:
    branches: [main, develop, docker]
  pull_request:
    branches: [main, develop, docker]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn install

      - name: Use Secret
        run: echo $SUPER_SECRET
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}

  testing:
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Tests
        run: mvn test

      - name: Use Var
        run: echo $SUPER_VARIABLE
        env:
          SUPER_VARIABLE: ${{ vars.SUPER_VARIABLE }}

      - name: Maven Checkstyle
        run: mvn checkstyle:checkstyle
